kibot:
  version: 1

outputs:
  # For more information: https://github.com/INTI-CMNB/KiBoM
  - name: 'https://github.com/yaqwsx/PcbDraw'
    comment: 'default green svg top'
    type: 'pcbdraw'
    dir: 'docs/img'
    options:
      # [boolean=false] render the bottom side of the board (default is top side)
      bottom: false
      # [string|list(string)=''] Name of the filter to mark components as not fitted.
      # A short-cut to use for simple cases where a variant is an overkill
      dnf_filter: ''
      # [number=300] [10,1200] dots per inch (resolution) of the generated image
      dpi: 300
      # [string='svg'] [svg,png,jpg] output format. Only used if no `output` is specified
      format: 'svg'
      # [list(string)=[]] list of components to highlight
      highlight: []
      # [list(string)=[]] list of libraries
      libs: ['/usr/share/pcbdraw/footprints/KiCAD-base']
      # [boolean=false] mirror the board
      mirror: false
      # [boolean=false] do not make holes transparent
      no_drillholes: false
      # [string='%f-%i%v.%x'] name for the generated file. Affected by global options
      output: '%f-%i%v.%x'
      # [boolean=false] show placeholder for missing components
      placeholder: false
      # [dict|None] replacements for PCB references using components (lib:component)
      remap:
      # [list(string)|string=none] [none,all] list of components to draw, can be also a string for none or all.
      # The default is none
      show_components: none
      # [string|dict] PCB style (colors). An internal name, the name of a JSON file or the style options
      style: '/usr/share/pcbdraw/styles/jlcpcb-green-hasl.json'
      # [string=''] Board variant to apply
      variant: ''
      # [boolean=false] render V-CUTS on the Cmts.User layer
      vcuts: false
      # [string='visible'] [visible,all,none] using visible only the warnings about components in the visible side are generated
      warnings: 'none'

  - name: 'https://github.com/yaqwsx/PcbDraw'
    comment: 'default green svg top'
    type: 'pcbdraw'
    dir: 'docs/img'
    options:
      # [boolean=false] render the bottom side of the board (default is top side)
      bottom: true
      # [string|list(string)=''] Name of the filter to mark components as not fitted.
      # A short-cut to use for simple cases where a variant is an overkill
      dnf_filter: ''
      # [number=300] [10,1200] dots per inch (resolution) of the generated image
      dpi: 300
      # [string='svg'] [svg,png,jpg] output format. Only used if no `output` is specified
      format: 'svg'
      # [list(string)=[]] list of components to highlight
      highlight: []
      # [list(string)=[]] list of libraries
      libs: ['/usr/share/pcbdraw/footprints/KiCAD-base']
      # [boolean=false] mirror the board
      mirror: true
      # [boolean=false] do not make holes transparent
      no_drillholes: false
      # [string='%f-%i%v.%x'] name for the generated file. Affected by global options
      output: '%f-%i%v.%x'
      # [boolean=false] show placeholder for missing components
      placeholder: false
      # [dict|None] replacements for PCB references using components (lib:component)
      remap:
      # [list(string)|string=none] [none,all] list of components to draw, can be also a string for none or all.
      # The default is none
      show_components: none
      # [string|dict] PCB style (colors). An internal name, the name of a JSON file or the style options
      style: '/usr/share/pcbdraw/styles/jlcpcb-green-hasl.json'
      # [string=''] Board variant to apply
      variant: ''
      # [boolean=false] render V-CUTS on the Cmts.User layer
      vcuts: false
      # [string='visible'] [visible,all,none] using visible only the warnings about components in the visible side are generated
      warnings: 'none'
